# Generated by Django 2.2.17 on 2024-03-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0015_auto_20240316_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrepresentativespecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_representative_species', to='protein.Species'),
        ),
    ]
