# Generated by Django 2.2.17 on 2025-03-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0027_auto_20241204_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='sequence_hash_and_col',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='sequence_hash_and_col_main',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
