# Generated by Django 2.2.17 on 2025-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0028_auto_20250307_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='sequence_hash_and_col',
            field=models.TextField(null=True, unique=True),
        ),
    ]
