# Generated by Django 2.2.17 on 2025-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0029_auto_20250307_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='sequence_dup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='sequence_hash',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='sequence_hash_col',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ligand',
            unique_together={('sequence_hash', 'sequence_hash_col', 'sequence_dup')},
        ),
        migrations.AlterIndexTogether(
            name='ligand',
            index_together={('sequence_hash', 'sequence_hash_col')},
        ),
        migrations.AddIndex(
            model_name='ligand',
            index=models.Index(fields=['sequence_hash'], name='sequence_hash_index'),
        ),
        migrations.RemoveField(
            model_name='ligand',
            name='sequence_hash_and_col',
        ),
    ]
