# Generated by Django 2.2.17 on 2025-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0030_auto_20250307_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='sequence_dup',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='sequence_hash_col',
            field=models.TextField(default=None, null=True),
        ),
    ]
