# Generated by Django 2.2.17 on 2025-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0032_auto_20250307_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='sequence_hash',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='sequence_hash_and_col_main',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
