# Generated by Django 2.2.17 on 2025-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0033_auto_20250307_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='sequence_dup',
            field=models.IntegerField(null=True),
        ),
    ]
