# Generated by Django 2.2.17 on 2025-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligand', '0034_auto_20250308_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='sequence_dup',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
