# Generated by Django 2.2.17 on 2024-02-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Similarity', models.IntegerField()),
                ('Protein1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_protein1', to='protein.Protein')),
                ('Protein2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_protein2', to='protein.Protein')),
                ('ProteinFamily1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_protein_family1', to='protein.ProteinFamily')),
                ('ProteinFamily2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_protein_family2', to='protein.ProteinFamily')),
            ],
        ),
    ]
