# Generated by Django 2.2.17 on 2024-02-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0002_classsimilarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsimilarity',
            old_name='Protein1',
            new_name='protein1',
        ),
        migrations.RenameField(
            model_name='classsimilarity',
            old_name='Protein2',
            new_name='protein2',
        ),
        migrations.RenameField(
            model_name='classsimilarity',
            old_name='ProteinFamily1',
            new_name='protein_family1',
        ),
        migrations.RenameField(
            model_name='classsimilarity',
            old_name='ProteinFamily2',
            new_name='protein_family2',
        ),
        migrations.RenameField(
            model_name='classsimilarity',
            old_name='Similarity',
            new_name='similarity',
        ),
    ]
