# Generated by Django 2.2.17 on 2024-03-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0003_auto_20240226_1833'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classsimilarity',
            constraint=models.UniqueConstraint(fields=('protein_family1', 'protein_family2'), name='unique_class_similarity_protein_family'),
        ),
        migrations.AddConstraint(
            model_name='classsimilarity',
            constraint=models.UniqueConstraint(fields=('protein1', 'protein2'), name='unique_class_similarity_protein'),
        ),
    ]
