# Generated by Django 2.2.17 on 2024-03-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0004_auto_20240307_1820'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classsimilarity',
            name='unique_class_similarity_protein',
        ),
        migrations.RemoveField(
            model_name='classsimilarity',
            name='protein1',
        ),
        migrations.RemoveField(
            model_name='classsimilarity',
            name='protein2',
        ),
        migrations.AddField(
            model_name='classsimilarity',
            name='ident_protein1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_ident_protein1', to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='classsimilarity',
            name='ident_protein2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_ident_protein2', to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='classsimilarity',
            name='identity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsimilarity',
            name='similar_protein1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_similar_protein1', to='protein.Protein'),
        ),
        migrations.AddField(
            model_name='classsimilarity',
            name='similar_protein2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_similar_protein2', to='protein.Protein'),
        ),
    ]
