# Generated by Django 2.2.17 on 2024-03-14 19:36

import alignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0005_auto_20240314_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSimilarityTies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'IDENTITY'), (1, 'SIMILARITY')], default=1)),
                ('class_similarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_ties_class_similarity', to='alignment.ClassSimilarity')),
                ('protein1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_ties_protein1', to='protein.Protein')),
                ('protein2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_ties_protein2', to='protein.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='classsimilarity',
            name='ties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_ties', to='alignment.ClassSimilarityTies'),
        ),
    ]
