# Generated by Django 2.2.17 on 2024-03-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0006_auto_20240314_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsimilarity',
            name='ties',
        ),
    ]
