# Generated by Django 2.2.17 on 2024-03-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0007_remove_classsimilarity_ties'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSimilarityTies',
            new_name='ClassSimilarityTie',
        ),
    ]
