# Generated by Django 2.2.17 on 2024-03-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0008_auto_20240315_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsimilarity',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_species', to='protein.Species'),
        ),
    ]
