# Generated by Django 2.2.17 on 2024-03-16 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0010_remove_classsimilarity_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_species', to='protein.ProteinFamily')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.Species')),
            ],
        ),
    ]
