# Generated by Django 2.2.17 on 2024-03-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0018_auto_20231026_2107'),
        ('alignment', '0011_representativespecies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepresentativeSpecies',
            new_name='ClassRepresentativeSpecies',
        ),
    ]
