# Generated by Django 2.2.17 on 2024-03-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0012_auto_20240316_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrepresentativespecies',
            name='protein_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_representative_species', to='protein.ProteinFamily'),
        ),
    ]
