# Generated by Django 2.2.17 on 2024-03-16 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0013_auto_20240316_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsimilaritytie',
            name='class_similarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_tie_class_similarity', to='alignment.ClassSimilarity'),
        ),
        migrations.AlterField(
            model_name='classsimilaritytie',
            name='protein1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_tie_protein1', to='protein.Protein'),
        ),
        migrations.AlterField(
            model_name='classsimilaritytie',
            name='protein2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_similarity_tie_protein2', to='protein.Protein'),
        ),
    ]
