# Generated by Django 2.2.17 on 2024-03-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignment', '0014_auto_20240316_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrepresentativespecies',
            name='protein_family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_representative_protein_family', to='protein.ProteinFamily'),
        ),
        migrations.AlterField(
            model_name='classrepresentativespecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_representative_species', to='protein.Species'),
        ),
        migrations.AddConstraint(
            model_name='classsimilarity',
            constraint=models.UniqueConstraint(fields=('similar_protein1', 'similar_protein2'), name='unique_class_similarity_similar_proteins'),
        ),
        migrations.AddConstraint(
            model_name='classsimilarity',
            constraint=models.UniqueConstraint(fields=('ident_protein1', 'ident_protein2'), name='unique_class_similarity_ident_proteins'),
        ),
        migrations.AddConstraint(
            model_name='classsimilaritytie',
            constraint=models.UniqueConstraint(fields=('protein1', 'protein2', 'type'), name='unique_class_similarity_tie_proteins_type'),
        ),
    ]
